### ISSUE TITLE
EncryptPad is incapable of staying in MacOS dock between reboots - turns into question mark icon

### ISSUE THREAD

**Issue by Zuldra** [evpo/EncryptPad#70] opened 2017-07-22 18:47 UTC
Hello,

I have tested & confirmed this problem on multiple Apple computers, all running MacOS Sierra.
It's happening on a Mac Pro desktop computer, a fresh install MacBook Pro 2017, and a fresh install MacBook Air.

Steps to reproduce:

1) Download EncryptPad
2) Open EncryptPad0_3_2_5.dmg file and copy the EncryptPad application into the Applications folder
3) Launch EncryptPad from the Applications folder
4) Right click on EncryptPad in the Dock, and press "Keep in Dock"
    (Alternatively, rearrange the EncryptPad icon in the dock so that it auto-keeps)
5) Reboot MacOS
6) EncryptPad icon in dock is now a QUESTION MARK and is **unusable**, and **unlaunchable**.

Also: If you attempt to drag and drop EncryptPad from the Applications folder into the Dock, it will not work correctly: You will see an EncryptPad icon in the dock, but when you click on this icon a *different* EncryptPad will open (so that you see 2 separate EncryptPad icons), and the one you clicked on will not be running.

**Comment by evpo** [comment] 2017-07-24 02:11
Thanks for reporting. I will upgrade to Sierra and see what's going on.

**Comment by evpo** [comment] 2017-07-25 09:52
I tried to reproduce your steps after upgrading to Sierra on a MacBook Pro. Not sure if you missed a step but between steps 2 and 3, there was a security procedure that I needed to do. MacOS reports that the application was downloaded from the internet and can be dangerous. It requires the user to hold Ctrl key and open the application by selecting Open from the context menu. After doing it once, the application opens normally.

Other than the comment above I didn't notice any issues before and after rebooting. Could it be an antivirus or another corporate security system that interferes with the application?

**Comment by BrookElliot** [comment] 2017-07-25 15:41
evpo,

Thanks for the follow up and attention here.

The security confirmation between steps 2 and 3 was indeed executed. We pressed "open".

There is no corporate internet here of any kind. These problems are occurring on newly purchased Macs, and in the case of the Airs, freshly clean-installed Macs.

To follow up I have just asked my co-worker to test EncryptPad on his newly purchased MacBook which is less than 2 weeks old.

On his home internet, he is also getting the ? mark after reboot. It may be possible that you are not getting it because you have upgraded to Sierra.

Zuldra

**Comment by Zuldra** [comment] 2017-07-25 15:43
evpo,

Thanks for the follow up and attention here.

The security confirmation between steps 2 and 3 was indeed executed. We pressed "open".

There is no corporate internet here of any kind. These problems are occurring on newly purchased Macs, and in the case of the Airs, freshly clean-installed Macs.

To follow up I have just asked my co-worker to test EncryptPad on his newly purchased MacBook which is less than 2 weeks old.

On his home internet, he is also getting the ? mark after reboot. It may be possible that you are not getting it because you have upgraded to Sierra.

Zuldra

**Comment by evpo** [comment] 2017-07-26 01:45
Zuldra,

Yes, it's quite possible. I will see if I can get my hands on a fresh install. This issue is disturbing.

Have you tried to download and install all system updates that Apple has issued for Sierra? Maybe they have fixed something after making the preinstalled macOS on the new hardware.

**Comment by evpo** [comment] 2017-07-26 03:09
I would like to clarify a few things about step 2 to ensure that we are doing the same thing:
1. After mounting dmg, do you drag and drop EncryptPad to the "Applications" shortcut in the dmg file? Or you drag and drop the app to the system Applications folder outside of the dmg file? (I dropped it to the Applications in the dmg file when I tested).
2. Can you follow steps 2 to 4 and unmount the dmg file instead of rebooting? Will you have the same effect?
3. What's your Sierra version number 10.12.X?

I found [this question](https://discussions.apple.com/thread/5056007?tstart=0) with similar symptoms. It says that question mark in Dock appears if the dock shortcut points to an application that has been removed or renamed. Is it possible that it points to the file in the mounted dmg file and becomes unavailable after reboot because the dmg file is no longer mounted.

**Comment by evpo** [comment] 2017-07-26 03:23
I also found [this question](https://apple.stackexchange.com/questions/254684/macos-sierra-missing-app-icon-in-dock-and-check-for-updates-fails-for-certa) about a new Sierra GPR issue that looks very similar to yours. They suggest to run a command in terminal as follows:

    xattr -dr com.apple.quarantine /Applications/Your.app

Replace *Your.app* with *EncryptPad.app*. Try it and let me know if it helped. It should remove "com.apple.quarantine" attribute from the application files.

**Comment by Zuldra** [comment] 2017-07-26 03:38
evpo,

EncryptPad was being dragged from the DMG to the system Applications folder in a separate Finder window. Afterwards, the DMG is immediately unmounted/ejected. EncryptPad was never launched from the DMG, so no possibility that any link refers to the DMG. It's launched only from the Applications folder after it has been copied to the applications folder and the DMG ejected.

**Comment by Zuldra** [comment] 2017-07-26 03:40
> xattr -dr com.apple.quarantine /Applications/Your.app

> Replace Your.app with EncryptPad.app. Try it and let me know if it helped. It should remove > "com.apple.quarantine" attribute from the application files.


This worked and resolved the problem! I was able to reboot without getting a ? mark, and EncryptPad can be launched after reboot.

**Comment by Zuldra** [comment] 2017-07-26 03:43
I should note: After installing around 30 different apps on the fresh install, and having to press "Open" on various of them, and additionally having to go into System Preferences -> Security & Privacy -> and explicitly allow some of them -- EncryptPad was the only one that didn't work and required manually removing the quarantine attribute. Maybe there is some way to resolve this for other users who may be unaware of this extra step.

**Comment by evpo** [comment] 2017-07-26 03:57
I suspect it's because, unlike other software, EncryptPad is not signed by a commercial certificate. It uses OpenPGP for signing. You can find more information about it [here](http://evpo.net/encryptpad/#openpgp-signing).

**Comment by evpo** [comment] 2017-07-26 04:08
I linked this issue from the releases page to help others. I am closing it for now. However, we can still continue our conversation here and I might come back to this issue later. Unfortunately, security systems are becoming more sophisticated and restrictive.

**Closed** 2017-07-26 04:09 UTC
Labels: bug
